## CAPSTONE PROJECT - DATASCIENCE_2026

### DATA PREPARATION / PREPROCESSING

In [1]:
# IMPORTING ALL IMPORTANT LIBRARIES

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [2]:
# IMPORTING THE DATASET
df_telco=pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [3]:
# CHECKING DATASET CONTENTS

df_telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
# CHECKING FOR DATASET SHAPE

df_telco.shape

(7043, 21)

In [5]:
# CHECKING FOR DATA VALIDITY/CONSISTENCY

df_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
# CONVERTING COLUMN (TotalCharges) FROM OBJECT TO NUMERIC VALUES (FLOAT)

df_telco['TotalCharges'] = pd. to_numeric(df_telco['TotalCharges'], errors='coerce')
df_telco['TotalCharges'] = df_telco['TotalCharges'].fillna(0.0)

In [7]:
# RECHECKING FOR DATA VALIDIDT/CONSISTENCY

df_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [8]:
# REMOVING IRRELEVANT COLUMN (COLUMN ID)
# customerID: Dropped prior to modelling as it carries zero predictive value and introduces unnecessary noise/dimensionality.

df_telco = df_telco.drop(columns=['customerID'])

In [9]:
# REVIEWING DATAFRAME

df_telco.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
# REVIEWING DATAFRAME SHAPE
df_telco.shape

(7043, 20)

## TASK 1 — PREDICTING REVENUE (REGRESSION)
# Objective: Address the Finance team's request by predicting MonthlyCharges based on subscriber profiles.

In [11]:
# IMPORTING THE IMPORTANT LIBRARIES
# Target choice: TotalCharges is the lifetime revenue a customer has generated, so it is the natural "revenue" target. 

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, accuracy_score

In [12]:
# DEFINE FEATURES AND TARGET (TotalCharges & Churn excluded to prevent target leakage)

X = df_telco.drop(columns=['MonthlyCharges', 'TotalCharges', 'Churn'])
y = df_telco['MonthlyCharges']

In [13]:
# DISPLAY FEATURES & TARGET
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic)
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check

In [14]:
y.head()

0    29.85
1    56.95
2    53.85
3    42.30
4    70.70
Name: MonthlyCharges, dtype: float64

In [15]:
# 3. ENCODING CATEGORICAL DATA WITH ONE-HOT-ENCODER

X_encoded = pd.get_dummies(X, drop_first=True)

In [16]:
# DISPLAY ENCODED CATEGORICAL DATA(FEATUES)

X_encoded.head()

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,True,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,True,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [17]:
# SPLITTING DATASET INTO TRAINING & TESTING SETS

X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [18]:
# CREATING AN INSTANCE FOR THE REGRESSION ALGORITHM

modelReg = LinearRegression()
modelReg.fit(X_train, y_train)

LinearRegression()

In [19]:
# MODEL EXALUATION

y_pred = modelReg.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [20]:
# MODEL EVALUATION

print(f"-- FINANCE TASK: REGRESSION RESULTS ---")
print(f"Mean Absolute Error (MAE): ${mae:.2f}")
print(f"Root Mean Squared Error (RMSE): ${rmse:.2f}")
print(f"R-squared (R2 Score): {r2:.4f}")

-- FINANCE TASK: REGRESSION RESULTS ---
Mean Absolute Error (MAE): $0.79
Root Mean Squared Error (RMSE): $1.05
R-squared (R2 Score): 0.9988

In [21]:
# MAKING PREDICTIONS

y_pred

array([24.95966268, 24.98735779, 19.92427981, ..., 19.95950489,
       44.9247107 , 29.94193257], shape=(1409,))

In [22]:
# SUMMARY OF ANALYSIS

# METRIC                             VALUE    BUSINESS MEANING
# Mean Absolute Error (MAE)          $0.79:   On average, model estimates differ from actual monthly bills by only 79 cents.
# Root Mean Squared Error (RMSE)     $1.05:   Low variance in prediction errors, with extreme pricing outliers virtually non-existent.
# R-Squared (R_2)                    0.9988:  The feature set explains 99.88% of the variance in customer monthly billings.

In [23]:
# RECOMMENDATION TO THE FINANCIAL TEAM

# 1. Financial Assessment: The regression model achieves exceptional precision with an MAE of $0.79 on
#    average monthly charges ranging from $18.25 to $118.75.

# 2. This performance is highly robust and fully ready for deployment in Finance operations for monthly revenue 
#    forecasting and auto-generating dynamic quote estimates for new subscription packages.

## TASK 2 CUSTOMER CHURN (CLASSIFICATION)

### Objective: Build a cost-sensitive classification model to proactively flag customers likely to churn for the Retention team

In [24]:
# IMPORTING ALL REQUISITE LIBRARIES

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score, roc_auc_score, confusion_matrix, classification_report

In [25]:
# DISPLAYING DATASET

df_telco.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [26]:
df_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   float64
 19  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [27]:
# CREATING FEATURES(X) & TARGET(Y) 

x_feat = df_telco.drop(columns='Churn')
y_targ = df_telco['Churn'].map({'Yes': 1, 'No': 0})

In [28]:
x_feat.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

In [29]:
y_targ.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [30]:
# ENCODING FEATURES USING STANDARDSCALER

x_feat_encoded = pd.get_dummies(X, drop_first=True)

In [31]:
x_feat_encoded.head()

,SeniorCitizen,tenure,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,False,True,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,True,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,True,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

In [32]:
# SPLITTING DATA INTO TRAINING & TESTING SETS

xtrain,xtest,ytrain,ytest = train_test_split(x_feat_encoded, y_targ, test_size=0.2, random_state=42)

In [33]:
# SCALING XTRAIN, XTEST USING STANDARDSCALER

scaler = StandardScaler()
xtrain_scaled = scaler.fit_transform(xtrain)
xtest_scaled = scaler.transform(xtest)

In [34]:
# CREATING AN INSTANCE FOR THE ALGORITHM (LOGISTIC REGRESSION)

logR = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [35]:
# FITTING THE MODEL ON THE DATASET

logR.fit(xtrain_scaled, ytrain)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [36]:
# MODEL PREDICTION & EVALUATION 

ypred = logR.predict(xtest_scaled)
y_prob = logR.predict_proba(xtest_scaled)[:, 1]

In [37]:
# DISPLAYING YPRED & YPROB
ypred

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [38]:
y_prob

array([0.80086499, 0.22402844, 0.02357897, ..., 0.13257575, 0.05616722,
       0.66705284], shape=(1409,))

In [39]:
# DISPLAYING RESULTANT METRICS

print("--- RETENTION TASK: CLASSIFICATION METRICS ---")
print(f"Accuracy:  {accuracy_score(ytest, ypred):.4f}")
print(f"Recall:    {recall_score(ytest, ypred):.4f}  <-- Primary Business Metric")
print(f"Precision: {precision_score(ytest, ypred):.4f}")
print(f"ROC-AUC:   {roc_auc_score(ytest, y_prob):.4f}")

--- RETENTION TASK: CLASSIFICATION METRICS ---
Accuracy:  0.7559
Recall:    0.8231  <-- Primary Business Metric
Precision: 0.5248
ROC-AUC:   0.8604

In [40]:
# BUSINESS CONCLUSION FOR RETENTION TEAM

# Logistic Regression with Balanced Class Weights is selected. 
# Its 82.31% Recall successfully flags nearly 8 out of 10 potential churners. 
# The lower Precision (52.48%) means some stable customers receive retention outreach, 
# which is an acceptable business trade-off given that offering a discount/incentive to a 
# loyal customer carries far less cost than losing a customer entirely.

# TASK 3: SEGMENTING CUSTOMERS

## Objective: 
## Group customers into actionable marketing segments using K-Means Clustering

In [41]:
# IMPORTING REQUIRED PYTHON LIBRARIES

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [42]:
# DISPLAYING DATASET

df_telco.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [43]:
# CREATING FEATURES(X) & ENCODING

X_cluster = df_telco.drop(columns=['Churn'])
X_encoded = pd.get_dummies(X_cluster, drop_first=True)

In [44]:
# SCALING THE FEATURES(X) USING STANDARDSCALER

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)

In [45]:
# CREATING AN INSTANCE FOR THE ALGORITHM / FITTING THE MODEL & TRAINING IT

kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df_telco['Segment_Cluster'] = kmeans.fit_predict(X_scaled)

In [46]:
# DISPLAY SEGMENT CLUSTER

df_telco['Segment_Cluster']

0       0
1       1
2       1
3       0
4       1
       ..
7038    2
7039    2
7040    0
7041    1
7042    2
Name: Segment_Cluster, Length: 7043, dtype: int32

In [47]:
# CREATING PROFILE CLUSTERS FOR MARKETING CAMPAIGNS

cluster_profiles = df_telco.groupby('Segment_Cluster').agg({
    'tenure': 'mean',
    'MonthlyCharges': 'mean',
    'TotalCharges': 'mean',
    'Contract': lambda x: x.mode()[0],
    'InternetService': lambda x: x.mode()[0],
    'Churn': lambda x: (x == 'Yes').mean() * 100
}).rename(columns={'Churn': 'Observed_Churn_Rate_%'})

In [48]:
# DISPLAY CLUSTER PROFILES

print("--- MARKETING TASK: CLUSTER PERSONAS ---")
print(cluster_profiles)

--- MARKETING TASK: CLUSTER PERSONAS ---
                    tenure  MonthlyCharges  TotalCharges        Contract  \
Segment_Cluster
0                31.737537       42.028592   1496.033651  Month-to-month
1                15.538208       73.985356   1171.792048  Month-to-month
2                55.825238       91.874429   5152.327429        Two year
3                30.547182       21.079194    662.604784        Two year

                InternetService  Observed_Churn_Rate_%
Segment_Cluster
0                           DSL              24.926686
1                   Fiber optic              46.691042
2                   Fiber optic              14.714286
3                            No               7.404980

In [49]:
# BUSINESS CONCLUSION FOR THE MARKETING TEAM

# Four actionable segments identified.
# The biggest opportunity is Segment 1 (new high-spenders on month-to-month) — high value 
# and high flight risk — where a contract-lock incentive protects the most revenue.